name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Slim Docker image
      id: meta_slim
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=slim
          type=sha,prefix=slim-

    - name: Extract metadata (tags, labels) for Fat Docker image
      id: meta_fat
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=fat
          type=sha,prefix=fat-

    - name: Build and push Slim Docker image
      id: push_slim
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta_slim.outputs.tags }}
        labels: ${{ steps.meta_slim.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GITHUB_ACTOR=${{ github.actor }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Fat Docker image
      id: push_fat
      uses: docker/build-push-action@v6
      with:
        context: .
        file: DockerfileFat
        push: true
        tags: ${{ steps.meta_fat.outputs.tags }}
        labels: ${{ steps.meta_fat.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GITHUB_ACTOR=${{ github.actor }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Generate artifact attestation (Slim)
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push_slim.outputs.digest }}
        push-to-registry: true

    - name: Generate artifact attestation (Fat)
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push_fat.outputs.digest }}
        push-to-registry: true
